version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres_data:/var/lib/postgresql/data
