version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flask-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teste
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres_data:/var/lib/postgresql/data
    networks:
      - net

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask-db:lastest
    container_name: flask_app
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/teste
    ports:
      - "6060:6060"
    networks:
      - net
    restart: always
    depends_on:
      - db


networks :
  net :
    driver : bridge